"""phase7_verifications

Revision ID: 0cc02233f33e
Revises: d1f79615c1d9
Create Date: 2026-08-10 13:42:52.669052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cc02233f33e'
down_revision: Union[str, None] = 'd1f79615c1d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hypothesis_verifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hypothesis_id', sa.String(), nullable=False),
    sa.Column('investigation_run_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='hypothesisverificationstatus'), nullable=False),
    sa.Column('verification_objective', sa.String(), nullable=True),
    sa.Column('initial_score', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('support_delta', sa.Float(), nullable=True),
    sa.Column('contradiction_delta', sa.Float(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigation_run_id'], ['investigation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypothesis_verifications_hypothesis_id'), 'hypothesis_verifications', ['hypothesis_id'], unique=False)
    op.create_index(op.f('ix_hypothesis_verifications_investigation_run_id'), 'hypothesis_verifications', ['investigation_run_id'], unique=False)
    op.create_index(op.f('ix_hypothesis_verifications_status'), 'hypothesis_verifications', ['status'], unique=False)
    op.create_table('verification_steps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('verification_id', sa.String(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.Enum('PLANNING', 'TOOL_CALL', 'TOOL_RESULT', 'EVIDENCE_EVALUATION', 'SYSTEM', name='verificationsteptype'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=True),
    sa.Column('objective', sa.String(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['verification_id'], ['hypothesis_verifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_steps_step_number'), 'verification_steps', ['step_number'], unique=False)
    op.create_index(op.f('ix_verification_steps_verification_id'), 'verification_steps', ['verification_id'], unique=False)
    op.add_column('hypothesis_evidence', sa.Column('verification_id', sa.String(), nullable=True))
    bind = op.get_bind()
    if bind.engine.name == 'postgresql':
        sa.Enum('INITIAL', 'VERIFICATION', name='evidenceorigin').create(bind)
        op.execute("ALTER TYPE hypothesisstatus ADD VALUE IF NOT EXISTS 'SUPPORTED'")
        op.execute("ALTER TYPE hypothesisstatus ADD VALUE IF NOT EXISTS 'WEAKENED'")
        op.execute("ALTER TYPE hypothesisstatus ADD VALUE IF NOT EXISTS 'INCONCLUSIVE'")

    op.add_column('hypothesis_evidence', sa.Column('origin', sa.Enum('INITIAL', 'VERIFICATION', name='evidenceorigin'), nullable=False, server_default='INITIAL'))
    op.create_index(op.f('ix_hypothesis_evidence_verification_id'), 'hypothesis_evidence', ['verification_id'], unique=False)
    op.create_foreign_key(None, 'hypothesis_evidence', 'hypothesis_verifications', ['verification_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hypothesis_evidence', type_='foreignkey')
    op.drop_index(op.f('ix_hypothesis_evidence_verification_id'), table_name='hypothesis_evidence')
    op.drop_column('hypothesis_evidence', 'origin')
    op.drop_column('hypothesis_evidence', 'verification_id')
    op.drop_index(op.f('ix_verification_steps_verification_id'), table_name='verification_steps')
    op.drop_index(op.f('ix_verification_steps_step_number'), table_name='verification_steps')
    op.drop_table('verification_steps')
    op.drop_index(op.f('ix_hypothesis_verifications_status'), table_name='hypothesis_verifications')
    op.drop_index(op.f('ix_hypothesis_verifications_investigation_run_id'), table_name='hypothesis_verifications')
    op.drop_index(op.f('ix_hypothesis_verifications_hypothesis_id'), table_name='hypothesis_verifications')
    op.drop_table('hypothesis_verifications')
    # ### end Alembic commands ###
