"""phase6_hypotheses

Revision ID: d1f79615c1d9
Revises: c68abe300270
Create Date: 2026-08-10 13:18:54.207010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1f79615c1d9'
down_revision: Union[str, None] = 'c68abe300270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hypotheses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('investigation_run_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('APPLICATION', 'DATABASE', 'INFRASTRUCTURE', 'CONFIGURATION', 'DEPLOYMENT', 'DEPENDENCY', 'TRAFFIC', 'AUTHENTICATION', 'UNKNOWN', name='hypothesiscategory'), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'UNDER_REVIEW', name='hypothesisstatus'), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('generation_source', sa.String(), nullable=True),
    sa.Column('reasoning_summary', sa.String(), nullable=True),
    sa.Column('missing_evidence', sa.JSON(), nullable=True),
    sa.Column('verification_requirements', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_run_id'], ['investigation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypotheses_investigation_run_id'), 'hypotheses', ['investigation_run_id'], unique=False)
    op.create_index(op.f('ix_hypotheses_rank'), 'hypotheses', ['rank'], unique=False)
    op.create_index(op.f('ix_hypotheses_status'), 'hypotheses', ['status'], unique=False)
    op.create_table('hypothesis_evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hypothesis_id', sa.String(), nullable=False),
    sa.Column('evidence_id', sa.String(), nullable=False),
    sa.Column('relationship', sa.Enum('SUPPORTS', 'CONTRADICTS', 'NEUTRAL', 'CONTEXT', name='evidencerelationshiptype'), nullable=False),
    sa.Column('strength', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='evidencestrength'), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypothesis_evidence_evidence_id'), 'hypothesis_evidence', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_hypothesis_evidence_hypothesis_id'), 'hypothesis_evidence', ['hypothesis_id'], unique=False)
    op.create_index(op.f('ix_hypothesis_evidence_relationship'), 'hypothesis_evidence', ['relationship'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hypothesis_evidence_relationship'), table_name='hypothesis_evidence')
    op.drop_index(op.f('ix_hypothesis_evidence_hypothesis_id'), table_name='hypothesis_evidence')
    op.drop_index(op.f('ix_hypothesis_evidence_evidence_id'), table_name='hypothesis_evidence')
    op.drop_table('hypothesis_evidence')
    op.drop_index(op.f('ix_hypotheses_status'), table_name='hypotheses')
    op.drop_index(op.f('ix_hypotheses_rank'), table_name='hypotheses')
    op.drop_index(op.f('ix_hypotheses_investigation_run_id'), table_name='hypotheses')
    op.drop_table('hypotheses')
    # ### end Alembic commands ###
