"""Add phase 4 models

Revision ID: d241c9490a14
Revises: ff99852dc60a
Create Date: 2026-08-09 15:09:13.340324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd241c9490a14'
down_revision: Union[str, None] = 'ff99852dc60a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        op.execute("ALTER TYPE evidencesourcetype ADD VALUE IF NOT EXISTS 'CODE'")
        op.execute("ALTER TYPE evidencesourcetype ADD VALUE IF NOT EXISTS 'GIT_CHANGE'")

    op.create_table('repositories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_type', sa.Enum('LOCAL', 'GIT', name='repositorysourcetype'), nullable=False),
    sa.Column('source_location', sa.String(), nullable=False),
    sa.Column('default_branch', sa.String(), nullable=True),
    sa.Column('current_commit', sa.String(), nullable=True),
    sa.Column('ingestion_status', sa.Enum('PENDING', 'INDEXING', 'READY', 'FAILED', name='ingestionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_repositories',
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('repository_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('incident_id', 'repository_id')
    )
    op.create_table('source_files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repository_id', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_files_path'), 'source_files', ['path'], unique=False)
    op.create_table('code_chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_file_id', sa.String(), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('symbol_name', sa.String(), nullable=True),
    sa.Column('chunk_type', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_chunks_symbol_name'), 'code_chunks', ['symbol_name'], unique=False)
    op.alter_column('evidence', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('investigation_steps', 'input_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('investigation_steps', 'output_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('log_entries', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log_entries', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('investigation_steps', 'output_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('investigation_steps', 'input_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('evidence', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_code_chunks_symbol_name'), table_name='code_chunks')
    op.drop_table('code_chunks')
    op.drop_index(op.f('ix_source_files_path'), table_name='source_files')
    op.drop_table('source_files')
    op.drop_table('incident_repositories')
    op.drop_table('repositories')
    # ### end Alembic commands ###
