"""Add log_entries table

Revision ID: ff99852dc60a
Revises: 6ce24a782562
Create Date: 2026-08-09 10:52:25.382234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff99852dc60a'
down_revision: Union[str, None] = '6ce24a782562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.Enum('DEBUG', 'INFO', 'WARN', 'ERROR', 'CRITICAL', name='loglevel'), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_entries_endpoint'), 'log_entries', ['endpoint'], unique=False)
    op.create_index(op.f('ix_log_entries_http_status'), 'log_entries', ['http_status'], unique=False)
    op.create_index(op.f('ix_log_entries_incident_id'), 'log_entries', ['incident_id'], unique=False)
    op.create_index(op.f('ix_log_entries_level'), 'log_entries', ['level'], unique=False)
    op.create_index(op.f('ix_log_entries_service'), 'log_entries', ['service'], unique=False)
    op.create_index(op.f('ix_log_entries_timestamp'), 'log_entries', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_entries_timestamp'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_service'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_level'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_incident_id'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_http_status'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_endpoint'), table_name='log_entries')
    op.drop_table('log_entries')
    # ### end Alembic commands ###
